pystran - Python package for structural analysis with trusses and beams 

(C) 2025-2026, Petr Krysl, pkrysl@ucsd.edu

# A gentle introduction to matrices in Python

This tutorial should to be executed line by line.


We begin with the standard imports:

In [67]:
import math
import numpy

Here is a Python list:

In [68]:
al = [1, 2, 3]

We can make and array from it:


In [69]:
am = numpy.array(al)
print(am)

[1 2 3]


A two dimensional array (matrix) can be made from a list of lists:


In [70]:
A = 1000.0 * numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A = ", A)

A =  [[1000. 2000. 3000.]
 [4000. 5000. 6000.]
 [7000. 8000. 9000.]]


We can access the type of the elements of the matrix and its shape:


In [71]:
print(f"Type ({A.dtype}) and shape ({A.shape}) of A")

Type (float64) and shape ((3, 3)) of A


Individual elements (entries) of the matrix can be accessed by their indices:


In [72]:
print("Top left - A[0, 0] = ", A[0, 0])
print("Bottom left - A[2, 0] = ", A[2, 0])
print("Top right - A[0, 2] = ", A[0, 2])
print("Bottom right - A[2, 2] = ", A[2, 2])

Top left - A[0, 0] =  1000.0
Bottom left - A[2, 0] =  7000.0
Top right - A[0, 2] =  3000.0
Bottom right - A[2, 2] =  9000.0


Indices are really the offsets of the rows and columns from the top left corner.
Therefore to access row r=2 and column c=3, we use `A[r-1, c-1] = A[1, 2]`.

So called slicing can be used to extract submatrices: 

In [73]:
print("Top row - A[0, :] = ", A[0, :])
print("Rightmost column - A[:, -1] = ", A[:, -1])

Top row - A[0, :] =  [1000. 2000. 3000.]
Rightmost column - A[:, -1] =  [3000. 6000. 9000.]


The colon means "all elements in the row/column". The minus sign means
"counting from the end".

A list like this


In [74]:
B = numpy.array([6, -7])

produces a vector.


In [75]:
print(B.shape)

(2,)


The length of this vector can be computed using the dot product of two vectors.


In [76]:
print("Length of B = ", math.sqrt(numpy.dot(B, B)))

Length of B =  9.219544457292887


Two vectors can be added or subtracted.

In [77]:
C = numpy.array([3, 2])
print("B + C = ", B + C)

B + C =  [ 9 -5]


The diagonal of the square matrix A

In [78]:
print("A = ", A)

A =  [[1000. 2000. 3000.]
 [4000. 5000. 6000.]
 [7000. 8000. 9000.]]


can be extracted as follows:


In [79]:
print("Diagonal of A = ", numpy.diag(A))

Diagonal of A =  [1000. 5000. 9000.]


Square matrices are often transposed:


In [80]:
print("Transpose of A = ", A.T)

Transpose of A =  [[1000. 4000. 7000.]
 [2000. 5000. 8000.]
 [3000. 6000. 9000.]]


Matrix is symmetric if it is equal to its transpose, i.e., A - A.T is the zero matrix:

In [81]:
print("A - A.T = ", A - A.T)
# This matrix is not symmetric.

A - A.T =  [[    0. -2000. -4000.]
 [ 2000.     0. -2000.]
 [ 4000.  2000.     0.]]


A matrix can be decomposed into its symmetric and antisymmetric part.
The symmetric part is `(A + A.T)/2`, the antisymmetric part is `(A - A.T)/2`.


In [82]:
As = (A + A.T) / 2
Aa = (A - A.T) / 2
print("Symmetric part of A = ", As)
print("Antisymmetric part of A = ", Aa)

Symmetric part of A =  [[1000. 3000. 5000.]
 [3000. 5000. 7000.]
 [5000. 7000. 9000.]]
Antisymmetric part of A =  [[    0. -1000. -2000.]
 [ 1000.     0. -1000.]
 [ 2000.  1000.     0.]]


Here is an identity matrix:


In [83]:
I = numpy.eye(4)

And a zero matrix:


In [84]:
Z = numpy.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Matrices can be added and subtracted if they have the same shape.


In [85]:
D = numpy.random.rand(3, 4)
E = numpy.random.rand(3, 4)

In [86]:
print("D = ", D)
print("E = ", E)
print("E+D = ", E + D)

D =  [[0.01195037 0.80355831 0.2903414  0.32631809]
 [0.82886132 0.14171899 0.0262558  0.01697893]
 [0.49517733 0.3098499  0.27301667 0.98711164]]
E =  [[0.11223945 0.6547963  0.39327238 0.07973854]
 [0.77243785 0.44901269 0.99249051 0.80827018]
 [0.14289298 0.74489043 0.60152828 0.91918071]]
E+D =  [[0.12418982 1.45835462 0.68361379 0.40605662]
 [1.60129917 0.59073168 1.01874631 0.82524911]
 [0.63807031 1.05474032 0.87454495 1.90629235]]


If we are not interested in as many decimal places, we can use the printoptions.  


In [87]:
with numpy.printoptions(precision=3):
    print("E+D = ", E + D)

E+D =  [[0.124 1.458 0.684 0.406]
 [1.601 0.591 1.019 0.825]
 [0.638 1.055 0.875 1.906]]


Matrices can be multiplied by scalars.

In [88]:
print("2000 * D = ", 2000 * D)

2000 * D =  [[  23.90074769 1607.11662636  580.68280384  652.63617534]
 [1657.722645    283.43797841   52.51159842   33.95786037]
 [ 990.35465011  619.6997963   546.0333399  1974.2232716 ]]


Matrices can be multiplied together if they have compatible shapes (the number
of columns in the first matrix matches the number of rows of the second
matrix). There is a function for matrix multiplication called `dot`.


In [89]:
F = numpy.random.rand(4, 3)
G = numpy.random.rand(4, 3)
print("F = ", F)
print("G = ", G)


F =  [[0.24348113 0.05424965 0.8003134 ]
 [0.58260406 0.05002261 0.16991127]
 [0.84815427 0.88284183 0.00703235]
 [0.77426377 0.9517243  0.95429659]]
G =  [[0.07522285 0.51171928 0.51873824]
 [0.93320296 0.10106423 0.65381696]
 [0.99376063 0.95069741 0.87096454]
 [0.20354611 0.99891122 0.56055869]]


We cannot multiply F and G because they do not have compatible shapes.


In [90]:
try:
    print("F*G = ", numpy.dot(F, G))
except ValueError:
    print('Incompatible!')       


Incompatible!


But we can multiply `F` and `G.T` because they have compatible shapes.


In [91]:
print("F*G.T = ", numpy.dot(F, G.T))

F*G.T =  [[0.4612291  0.75595848 0.99058155 0.55237285]
 [0.15756214 0.6598342  0.77451204 0.26380018]
 [0.51921571 0.88532167 1.68830269 1.05846116]
 [1.04028813 1.44266582 2.50539317 1.64322571]]


Vectors can be used in the so called outer product to produce matrices.


In [92]:
B = numpy.array([1, 2, 3, 4])
print("B = ", B)
print("Outer product of B with itself = \n ", numpy.outer(B, B))

B =  [1 2 3 4]
Outer product of B with itself = 
  [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


The inverse of a matrix can be computed using the function `inv`.


In [93]:
K = numpy.array([[1, 2], [3, 4]])
print("K inverse = ", numpy.linalg.inv(K))
print("K*K inverse = ", numpy.dot(K, numpy.linalg.inv(K)))


K inverse =  [[-2.   1. ]
 [ 1.5 -0.5]]
K*K inverse =  [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


We should get identity matrix (within some numerical accuracy margins).

Some matrices are known to be singular, i.e., their inverse does not exist.


In [94]:
K = 0.1 * numpy.outer(B, B)
try:
    numpy.linalg.inv(K)
except ValueError:
    print('Yep, singular!')

Yep, singular!


That should not surprise us: all the rows in the matrix are linearly
dependent on the first one.


In [95]:
with numpy.printoptions(precision=3):
    print("K = ", K)

K =  [[0.1 0.2 0.3 0.4]
 [0.2 0.4 0.6 0.8]
 [0.3 0.6 0.9 1.2]
 [0.4 0.8 1.2 1.6]]


We will work with partitioned matrices in `pystran`. Slicing can be used to
extract the submatrices.

This particular matrix

In [96]:
K = numpy.array(
    [
        [266.78, 69.68, -197.1, 0.0, -69.68, -69.68, 0.0, 0.0],
        [69.68, 168.23, 0.0, 0.0, -69.68, -69.68, 0.0, -98.55],
        [-197.1, 0.0, 197.1, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [-69.68, -69.68, 0.0, 0.0, 69.68, 69.68, 0.0, 0.0],
        [-69.68, -69.68, 0.0, 0.0, 69.68, 69.68, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, -98.55, 0.0, 0.0, 0.0, 0.0, 0.0, 98.55],
    ]
)

is for a truss structure with
four joints (i.e. 8 total degrees of freedom), out of which one joint is free
to move (2 free degrees of freedom) and the others are pinned.

This matrix therefore has dimension


In [97]:
print("K shape = ", K.shape)

K shape =  (8, 8)


and the first 2 rows and first 2 columns are for the free degrees of freedom.


In [98]:
with numpy.printoptions(precision=2):
    print("K = \n", K)

K = 
 [[ 266.78   69.68 -197.1     0.    -69.68  -69.68    0.      0.  ]
 [  69.68  168.23    0.      0.    -69.68  -69.68    0.    -98.55]
 [-197.1     0.    197.1     0.      0.      0.      0.      0.  ]
 [   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [ -69.68  -69.68    0.      0.     69.68   69.68    0.      0.  ]
 [ -69.68  -69.68    0.      0.     69.68   69.68    0.      0.  ]
 [   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [   0.    -98.55    0.      0.      0.      0.      0.     98.55]]


We will pull out four submatrices, such that
K = [[Kff, Kfd]
     [Kdf, Kdd]]
where Kff is 2x2, Kfd is 2x6, Kdf is 6x2, and Kdd is 6x6.

In [99]:
Kff = K[0:2, 0:2]
Kfd = K[0:2, 2:]
Kdf = K[2:, 0:2]
Kdd = K[2:, 2:]
with numpy.printoptions(precision=3):
    print("Kff = ", Kff)
with numpy.printoptions(precision=3):
    print("Kfd = ", Kfd)
with numpy.printoptions(precision=3):
    print("Kdf = ", Kdf)
with numpy.printoptions(precision=3):
    print("Kdd = ", Kdd)

Kff =  [[266.78  69.68]
 [ 69.68 168.23]]
Kfd =  [[-197.1     0.    -69.68  -69.68    0.      0.  ]
 [   0.      0.    -69.68  -69.68    0.    -98.55]]
Kdf =  [[-197.1     0.  ]
 [   0.      0.  ]
 [ -69.68  -69.68]
 [ -69.68  -69.68]
 [   0.      0.  ]
 [   0.    -98.55]]
Kdd =  [[197.1    0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.  ]
 [  0.     0.    69.68  69.68   0.     0.  ]
 [  0.     0.    69.68  69.68   0.     0.  ]
 [  0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.    98.55]]


The eigenvalues of the matrix can be instructive.


In [100]:
Kinfo = numpy.linalg.eig(K)
print(Kinfo.eigenvalues)

[ 4.74502319e+02+0.00000000e+00j  2.67612630e+02+0.00000000e+00j
  1.27905051e+02+0.00000000e+00j -9.77235109e-15+1.37192137e-14j
 -9.77235109e-15-1.37192137e-14j -1.40364985e-47+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]


The matrix K is singular: look for those (practically or actually) zero eigenvalues.