[pystran](https://github.com/PetrKryslUCSD/pystran) - Python package for structural analysis with trusses and beams 

(C) 2025-2026, Petr Krysl, pkrysl@ucsd.edu

# A gentle introduction to matrices in Python

This tutorial should be executed line by line.


We begin with the standard imports:

In [ ]:
import math
import scipy
import numpy

Here is a Python list:

In [36]:
al = [1, 2, 3]

We can make and array from it:


In [37]:
am = numpy.array(al)
print(am)

[1 2 3]


A two dimensional array (matrix) can be made from a list of lists:


In [38]:
A = 1000.0 * numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A = ", A)

A =  [[1000. 2000. 3000.]
 [4000. 5000. 6000.]
 [7000. 8000. 9000.]]


We can access the type of the elements of the matrix and its shape:


In [39]:
print(f"Type ({A.dtype}) and shape ({A.shape}) of A")

Type (float64) and shape ((3, 3)) of A


Individual elements (entries) of the matrix can be accessed by their indices:


In [40]:
print("Top left - A[0, 0] = ", A[0, 0])
print("Bottom left - A[2, 0] = ", A[2, 0])
print("Top right - A[0, 2] = ", A[0, 2])
print("Bottom right - A[2, 2] = ", A[2, 2])

Top left - A[0, 0] =  1000.0
Bottom left - A[2, 0] =  7000.0
Top right - A[0, 2] =  3000.0
Bottom right - A[2, 2] =  9000.0


Indices are really the offsets of the rows and columns from the top left corner.
Therefore to access row r=2 and column c=3, we use `A[r-1, c-1] = A[1, 2]`.

So called slicing can be used to extract submatrices: 

In [41]:
print("Top row - A[0, :] = ", A[0, :])
print("Rightmost column - A[:, -1] = ", A[:, -1])

Top row - A[0, :] =  [1000. 2000. 3000.]
Rightmost column - A[:, -1] =  [3000. 6000. 9000.]


The colon means "all elements in the row/column". The minus sign means
"counting from the end".

A list like this


In [42]:
B = numpy.array([6, -7])

produces a vector.


In [43]:
print(B.shape)

(2,)


The length of this vector can be computed using the dot product of two vectors.


In [44]:
print("Length of B = ", math.sqrt(numpy.dot(B, B)))

Length of B =  9.219544457292887


Two vectors can be added or subtracted.

In [45]:
C = numpy.array([3, 2])
print("B + C = ", B + C)

B + C =  [ 9 -5]


The diagonal of the square matrix A

In [46]:
print("A = ", A)

A =  [[1000. 2000. 3000.]
 [4000. 5000. 6000.]
 [7000. 8000. 9000.]]


can be extracted as follows:


In [47]:
print("Diagonal of A = ", numpy.diag(A))

Diagonal of A =  [1000. 5000. 9000.]


Square matrices are often transposed:


In [48]:
print("Transpose of A = ", A.T)

Transpose of A =  [[1000. 4000. 7000.]
 [2000. 5000. 8000.]
 [3000. 6000. 9000.]]


Matrix is symmetric if it is equal to its transpose, i.e., A - A.T is the zero matrix:

In [49]:
print("A - A.T = ", A - A.T)
# This matrix is not symmetric.

A - A.T =  [[    0. -2000. -4000.]
 [ 2000.     0. -2000.]
 [ 4000.  2000.     0.]]


A matrix can be decomposed into its symmetric and antisymmetric part.
The symmetric part is `(A + A.T)/2`, the antisymmetric part is `(A - A.T)/2`.


In [50]:
As = (A + A.T) / 2
Aa = (A - A.T) / 2
print("Symmetric part of A = ", As)
print("Antisymmetric part of A = ", Aa)

Symmetric part of A =  [[1000. 3000. 5000.]
 [3000. 5000. 7000.]
 [5000. 7000. 9000.]]
Antisymmetric part of A =  [[    0. -1000. -2000.]
 [ 1000.     0. -1000.]
 [ 2000.  1000.     0.]]


Here is an identity matrix:


In [51]:
I = numpy.eye(4)

And a zero matrix:


In [52]:
Z = numpy.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Matrices can be added and subtracted if they have the same shape.


In [53]:
D = numpy.random.rand(3, 4)
E = numpy.random.rand(3, 4)

In [54]:
print("D = ", D)
print("E = ", E)
print("E+D = ", E + D)

D =  [[0.1236213  0.31134214 0.58152277 0.37706612]
 [0.26760555 0.25345677 0.26935059 0.18312811]
 [0.46711288 0.39165849 0.28082518 0.9750959 ]]
E =  [[0.10333978 0.9467763  0.42181382 0.86136651]
 [0.76787199 0.56199417 0.04452046 0.68684972]
 [0.34837537 0.67498371 0.94420203 0.32976216]]
E+D =  [[0.22696108 1.25811844 1.00333659 1.23843262]
 [1.03547754 0.81545094 0.31387105 0.86997783]
 [0.81548825 1.0666422  1.22502721 1.30485806]]


If we are not interested in as many decimal places, we can use the printoptions.  


In [55]:
with numpy.printoptions(precision=3):
    print("E+D = ", E + D)

E+D =  [[0.227 1.258 1.003 1.238]
 [1.035 0.815 0.314 0.87 ]
 [0.815 1.067 1.225 1.305]]


Matrices can be multiplied by scalars.

In [56]:
print("2000 * D = ", 2000 * D)

2000 * D =  [[ 247.24259833  622.68428427 1163.04553305  754.13223368]
 [ 535.2111014   506.91354279  538.70117525  366.25622368]
 [ 934.22575386  783.31697018  561.65036977 1950.19180911]]


Matrices can be multiplied together if they have compatible shapes (the number
of columns in the first matrix matches the number of rows of the second
matrix). There is a function for matrix multiplication called `dot`.


In [57]:
F = numpy.random.rand(4, 3)
G = numpy.random.rand(4, 3)
print("F = ", F)
print("G = ", G)


F =  [[0.75793271 0.56681211 0.63071999]
 [0.05055242 0.06382918 0.29543918]
 [0.33418526 0.07927034 0.55116681]
 [0.19428106 0.28719004 0.8103243 ]]
G =  [[0.3841393  0.08061274 0.41528272]
 [0.86324597 0.58240924 0.73434171]
 [0.40134708 0.3049942  0.16392754]
 [0.05748635 0.7786304  0.59399818]]


We cannot multiply F and G because they do not have compatible shapes.


In [58]:
try:
    print("F*G = ", numpy.dot(F, G))
except ValueError:
    print('Incompatible!')       


Incompatible!


But we can multiply `F` and `G.T` because they have compatible shapes.


In [59]:
print("F*G.T = ", numpy.dot(F, G.T))

F*G.T =  [[0.59877114 1.44756297 0.58046086 0.85955445]
 [0.1472554  0.29776719 0.08818721 0.22809575]
 [0.36365395 0.73939664 0.24865269 0.40832547]
 [0.43429585 0.93002942 0.2983999  0.71611457]]


Vectors can be used in the so called outer product to produce matrices.


In [60]:
B = numpy.array([1, 2, 3, 4])
print("B = ", B)
print("Outer product of B with itself = \n ", numpy.outer(B, B))

B =  [1 2 3 4]
Outer product of B with itself = 
  [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


The inverse of a matrix can be computed using the function `inv`.


In [61]:
K = numpy.array([[1, 2], [3, 4]])
print("K inverse = ", numpy.linalg.inv(K))
print("K*K inverse = ", numpy.dot(K, numpy.linalg.inv(K)))


K inverse =  [[-2.   1. ]
 [ 1.5 -0.5]]
K*K inverse =  [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


We should get identity matrix (within some numerical accuracy margins).

Some matrices are known to be singular, i.e., their inverse does not exist.


In [62]:
K = 0.1 * numpy.outer(B, B)
try:
    numpy.linalg.inv(K)
except ValueError:
    print('Yep, singular!')

Yep, singular!


That should not surprise us: all the rows in the matrix are linearly
dependent on the first one.


In [63]:
with numpy.printoptions(precision=3):
    print("K = ", K)

K =  [[0.1 0.2 0.3 0.4]
 [0.2 0.4 0.6 0.8]
 [0.3 0.6 0.9 1.2]
 [0.4 0.8 1.2 1.6]]


We will work with partitioned matrices in `pystran`. Slicing can be used to
extract the submatrices.

This particular matrix

In [64]:
K = numpy.array(
    [
        [266.78, 69.68, -197.1, 0.0, -69.68, -69.68, 0.0, 0.0],
        [69.68, 168.23, 0.0, 0.0, -69.68, -69.68, 0.0, -98.55],
        [-197.1, 0.0, 197.1, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [-69.68, -69.68, 0.0, 0.0, 69.68, 69.68, 0.0, 0.0],
        [-69.68, -69.68, 0.0, 0.0, 69.68, 69.68, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, -98.55, 0.0, 0.0, 0.0, 0.0, 0.0, 98.55],
    ]
)

is for a truss structure with
four joints (i.e. 8 total degrees of freedom), out of which one joint is free
to move (2 free degrees of freedom) and the others are pinned.

This matrix therefore has dimension


In [65]:
print("K shape = ", K.shape)

K shape =  (8, 8)


and the first 2 rows and first 2 columns are for the free degrees of freedom.


In [66]:
with numpy.printoptions(precision=2):
    print("K = \n", K)

K = 
 [[ 266.78   69.68 -197.1     0.    -69.68  -69.68    0.      0.  ]
 [  69.68  168.23    0.      0.    -69.68  -69.68    0.    -98.55]
 [-197.1     0.    197.1     0.      0.      0.      0.      0.  ]
 [   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [ -69.68  -69.68    0.      0.     69.68   69.68    0.      0.  ]
 [ -69.68  -69.68    0.      0.     69.68   69.68    0.      0.  ]
 [   0.      0.      0.      0.      0.      0.      0.      0.  ]
 [   0.    -98.55    0.      0.      0.      0.      0.     98.55]]


We will pull out four submatrices, such that
K = [[Kff, Kfd]
     [Kdf, Kdd]]
where Kff is 2x2, Kfd is 2x6, Kdf is 6x2, and Kdd is 6x6.

In [67]:
Kff = K[0:2, 0:2]
Kfd = K[0:2, 2:]
Kdf = K[2:, 0:2]
Kdd = K[2:, 2:]
with numpy.printoptions(precision=3):
    print("Kff = ", Kff)
with numpy.printoptions(precision=3):
    print("Kfd = ", Kfd)
with numpy.printoptions(precision=3):
    print("Kdf = ", Kdf)
with numpy.printoptions(precision=3):
    print("Kdd = ", Kdd)

Kff =  [[266.78  69.68]
 [ 69.68 168.23]]
Kfd =  [[-197.1     0.    -69.68  -69.68    0.      0.  ]
 [   0.      0.    -69.68  -69.68    0.    -98.55]]
Kdf =  [[-197.1     0.  ]
 [   0.      0.  ]
 [ -69.68  -69.68]
 [ -69.68  -69.68]
 [   0.      0.  ]
 [   0.    -98.55]]
Kdd =  [[197.1    0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.  ]
 [  0.     0.    69.68  69.68   0.     0.  ]
 [  0.     0.    69.68  69.68   0.     0.  ]
 [  0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.    98.55]]


The eigenvalues of the matrix can be instructive.


In [68]:
Kinfo = numpy.linalg.eig(K)
print(Kinfo.eigenvalues)

[ 4.74502319e+02+0.00000000e+00j  2.67612630e+02+0.00000000e+00j
  1.27905051e+02+0.00000000e+00j -9.77235109e-15+1.37192137e-14j
 -9.77235109e-15-1.37192137e-14j -1.40364985e-47+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]


The matrix K is singular: look for those (practically or actually) zero eigenvalues.